### ISSUE TITLE
Problem with nil logger using Readme example

### ISSUE THREAD

**Issue by djumpen** [pharrisee/poloniex-api#11]
I'm trying to run your example to consume WS, but I'm getting panic due to nil pointer in logger
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6f7ba9]

goroutine 6 [running]:
github.com/miratronix/logpher.(*Logger).LevelEnabled(...)
        /home/djumpen/go/pkg/mod/github.com/miratronix/logpher@v0.0.0-20190916004947-6d251d5ad966/logger.go:49
github.com/miratronix/logpher.(*Logger).log(0x0, 0xd1c200, 0xc0000486b0, 0x2, 0x2)
        /home/djumpen/go/pkg/mod/github.com/miratronix/logpher@v0.0.0-20190916004947-6d251d5ad966/logger.go:55 +0x29
github.com/miratronix/logpher.(*Logger).Info(...)
        /home/djumpen/go/pkg/mod/github.com/miratronix/logpher@v0.0.0-20190916004947-6d251d5ad966/logger.go:34
github.com/miratronix/gows.(*Websocket).connect(0xc00012c000, 0x0, 0x0, 0x0, 0x0)
        /home/djumpen/go/pkg/mod/github.com/miratronix/gows@v0.0.0-20191101035019-f217ff4e7cb2/connection.go:15 +0x113
github.com/miratronix/gows.(*Websocket).reviver(0xc00012c000, 0xc00012a120)
        /home/djumpen/go/pkg/mod/github.com/miratronix/gows@v0.0.0-20191101035019-f217ff4e7cb2/connection.go:51 +0x53
created by github.com/miratronix/gows.(*Websocket).Connect
        /home/djumpen/go/pkg/mod/github.com/miratronix/gows@v0.0.0-20191101035019-f217ff4e7cb2/websocket.go:72 +0x92
```
I could fix it by initializing logger inside `NewWithCredentials` but I'm wondering how it works for you as it is now.

**Comment by djumpen** [comment]
Also HeartbeatInterval is required

**Comment by pharrisee** [comment]
ah, not sure what when on there, I must have committed a dev version by mistake.

I've switched back to using recws.

I'm using this version myself so I'm pretty sure it's ok.
